OPENAI_API_KEY = "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"

OPENAI_MODEL = "gpt-4"

NEO4J_URI = "neo4j+s://c8a0a9ad.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "OPZzBvAPjVFVol7h79DwGZL_uASFAnkJgNQ3Gj4m4KU"
