OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4"

NEO4J_URI = "neo4j+s://c8a0a9ad.databases.neo4j.io"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "OPZzBvAPjVFVol7h79DwGZL_uASFAnkJgNQ3Gj4m4KU"
